= Vein Toolbox Overview
:showtitle:
:revdate: 2020-05-05

== Overview
Finger/palm vein verification authenticates the user based on the human finger/palm vein patterns beneath the skin's surface. This toolbox specifies artefacts for finger/palm vein PAD testing and their production methods, referring to relevant research papers. While the focus of the toolbox is on finger/palm vein verification, this toolbox can also be applicable to other types of vein verification (e.g., dorsal hand or wrist vein verification), as they use the same technology to capture and match vein patterns.

== Vein Presentation Attacks
A vein presentation attack can be carried out through the following process:  

. Capture the vein image with Near Infra-Red (NIR) light or visible light.  
. Print or display the vein image on materials such as paper or screens to create the artefacts.
. Present the artefacts to the TOE.  

Vein presentation attacks can be categorized into the *print attack (NIR light image)*, *print attack (Visible light image)*, *print attack (Combined image)* and *video attack (Visible light image)* based on the TOE’s method to capture the vein image. The TOE can capture the vein image with NIR light and vein patterns appear as a series of dark lines in the image. The TOE can also capture the vein image with visible light and vein patterns appear as those lines with a limited red color component in the image because haemoglobin in vein absorbs red light making the vein pattern visible. 

The evaluator shall test *print attack (NIR light image)*, *print attack (visible light image)* and *print attack (combined image)* against those TOEs that use the NIR light, and *print attack (visible light image)*, *print attack (combined image)* and *video attack (visible light image)* against those TOEs that use the visible light. The *print attack (NIR light image)* is only applicable to a TOE that uses NIR light because the TOE that captures the vein image with visible light recognizes the vein pattern based on the intensity of particular color components (e.g red and green color components). The *video attack (visible light image)* is only applicable to a TOE that uses visible light because the TOE that captures the vein image with NIR light cannot recognize the vein pattern displayed on the computer screen or display because the whole screen or display appears as a single black image in NIR light.

== Vein Presentation Attack Detection
As for other biometric characteristics such as 2D face, texture patterns have been extensively analyzed for vein PAD based on the technology used for classification in computer vision, such as Local Binary Pattern (LBP). This method captures textural details and detect artefacts using a classifier such as a Support Vector Machine (SVM). Short video sequences, with the aid of techniques such as Eulerian video magnification, can also be used to amplify blood flow and thus detect printed artefacts. Deep Learning (DL) is another approach to detect artefacts using a Convolutional Neural Network (CNN) designed for vein PAD. These PAD technologies may achieve high detection accuracy over test vein image databases.

== Common Test Protocol
The presentation attacks mentioned above (i.e., *print attack (NIR light image)*, *print attack (visible light image)*, *print attack (combined image)* and *video attack (visible light image)*) shall be performed for vein PAD testing. In testing, the evaluator may use different type of scanners to capture vein images to create artefacts. The evaluator may also present those artefacts in various ways. Because it is not possible to cover all possible test scenarios, this toolbox defines a common test protocol to maintain consistency among PAD testing between different labs and enable efficient testing by referring to research papers. The evaluator shall follow the test protocols described below, in addition to guidance provided in <<PAD Toolbox Overview>> to conduct the PAD testing.
The tools and media for the creation of artefacts are defined for all tests in the <<Vein Toolbox Inventory>>. Each attack specifies which tools and media are to be used in the creation of artefacts for that test.

. Enrollment
+
The evaluator shall turn on the vein unlock and enroll the test users following instructions provided by the AGD guidance.

. Vein image capture
+
The evaluator shall capture vein images right after the enrolment of the test users under the same conditions to reduce the possibility that the artefacts are rejected because of the differences in illumination, background scene, and vein location.
+
* NIR light image
+
The evaluator shall capture the vein image from the target user with a scanner using NIR light. Subsequent sections and the <<Vein Toolbox Inventory>> explain which scanner the evaluator should use. The captured white and black vein image will be used for the *print attack (NIR light image)* and *print attack (combined image)*.
+
* Visible light image
+
The evaluator shall capture the vein image from the target user with a dSLR camera using visible light. Requirements for the camera are specified in <<Vein Toolbox Inventory>>. The captured color vein image will be used for the *print attack (visible light image)* and *print attack (combined image)*. Captured video of vein is used for *video attack (visible light image)*.

. Preprocess the vein image
+
* NIR light image
+
If the captured vein pattern image is not clearly visible, the evaluator shall preprocess the image to improve contrast of the vein pattern. The evaluator may use a pencil or image processing software to make the vein pattern clearly visible. The evaluator may use the either of tools, however, the evaluator's effort shall be within the attack potential required by <<BIOPP-Module>>. The evaluator shall also perform proper rescaling, so the printed vein image should be the same size as the real one.
+
* Visible light image
+
The evaluator may enhance the blue vein pattern for the printout to decrease the red color component in the pattern with a pencil by hand or with image processing software. The evaluator may not use image processing software as explained for NIR light images. The evaluator shall perform proper rescaling such that printed vein image is the same size as the real vein image.

. Artefact creation   
[loweralpha]
.. Artefact for *print attack (NIR light image)*
+
The evaluator shall print the vein image on paper with a printer specified in <<Vein Toolbox Inventory>>. The TOE can capture the vein patterns from such printed artefacts because carbon ink has a strong tendency to absorb NIR light much like hemoglobin in the vein, so visible dark lines (i.e., vein patterns) should appear on the printed artefacts.
+
.. Artefact for *print attack (visible light image)*
+
The evaluator shall print the vein image on paper with a printer specified in <<Vein Toolbox Inventory>>. The visible blue lines (i.e., vein patterns) should appear on the printed artefacts so that the TOE can recognize the patterns.
+
.. Artefact for *print attack (combined image)*
+
The evaluator shall create composite image artefacts that put the printed artefact for visible light vein image (b) on another printed artefact for NIR light vein image (a).
+
.. Artefact for *video attack (visible light image)*
+
The evaluator shall display the vein image on a screen specified in <<Vein Toolbox Inventory>>. The visible blue lines (i.e., vein patterns) should appear on the screen so that the TOE can recognize the patterns.

. Artefact presentation
+
* Presentation method for *print attack (NIR light image)*, *print attack (combined image)* and *print attack (combined image)*
+
The evaluator shall present the printed artefacts to the TOE in the following manner because each presentation method may have a different effect on the TOE’s presentation attack detection functionality.
+
**	Direct presentation
+
Present the artefact as it is to the TOE.
+
**	Presentation of the artefact with bottle/tube 
+
Present the artefact adhered to a bottle for palm vein verification or a round transparent tube (size of tube is the same size as finger) for finger vein verification (See Figure 5-27 of [1] in <<Vein Toolbox References>>)
+
**	Presentation of the artefact with wax
+
Cover the artefact with wax to simulate human tissue and present it to the TOE (See [2] in <<Vein Toolbox References>>)
+
**	Presentation of the artefact with real palm/finger 
+
Present the artefact adhered to a different user’s palm or finger (e.g. Figure 5-27 of [1] in <<Vein Toolbox References>>)

* Presentation method for *video attack (visible light image)*
+
The evaluator shall present the screen that displays the vein image to the TOE.

== Requirements for Tools
This section provides guidelines for selection of the scanner that captures NIR light vein images because requirements for the scanner cannot be explicitly specified in <<Vein Toolbox Inventory>>. The requirements for all other tools are specified in <<Vein Toolbox Inventory>>.

The following scanners are available for the evaluator and were used in the research papers from <<Vein Toolbox References>> to create artefacts.

* Commercial scanner  
+
The evaluator may purchase the TOE or similar type of commercial vein scanner to capture the vein image. This is the best choice if such a scanner is available at an affordable cost.

* In-house scanner
+
The evaluator may develop a vein scanner themselves by referring to publicly available information (e.g., [3] for finger vein and [4] for palm vein in <<Vein Toolbox References>>).

* Camera
+
The evaluator may capture vein images using a commercial NIR camera with NIR light source. The evaluator may convert a normal digital camera into a NIR camera by removing the IR cut-off filter (e.g., [2] and [5] in <<Vein Toolbox References>>) instead of purchasing a dedicated NIR camera.

In any case, cost and skill for using the scanner need to be within the scope of Basic attack potential from <<BIOSD>>. The evaluator should estimate the cost and skill for using the scanner referring to the relevant research papers at the time of testing and choose the one that can capture the clearest vein image.


== Test Items
The evaluator shall create artefacts defined in all test items listed in the <<Vein Verification List>>. The <<Vein Verification List>> specifies the species that must be created based on the type of biometric sensor.

<<PAD Toolbox Overview>> defines the required number of attempts for the independent testing and the maximum timeframe for both independent and penetration testing.

== Pass/Fail Criteria
If Pass/Fail Criteria is defined in the test items, then the evaluator shall follow them. Otherwise, the evaluator shall follow criteria defined in <<BIOSD>> and <<PAD Toolbox Overview>>.

== Reference Information 
The Vein Toolbox was created based on research papers listed in <<Vein Toolbox References>>. The evaluator should read them before conducting the PAD testing because they include more detailed information about PAD test methods.
