= Vein Toolbox Inventory
:showtitle:
:revdate: 2020-05-05

== Overview
This document specifies requirements for tools that are used to create vein image artefacts. The requirements for each tool are specified in the following tables. The evaluator may use any tools and materials to create vein image artefacts as long as they meet requirements specified below. The evaluator shall confirm that created artefacts show visible vein patterns (e.g., dark lines for NIR vein image).

The evaluator may use additional tools that are not specified here.

Some examples:

* The evaluator may use image processing software to enhance vein patterns.
+
In such cases, the evaluator may use any software, however, the evaluator shall visually confirm that the final image includes clear vein patterns.

== Tools Inventory
.Tool Requirements
[cols=".^1,.^1,3",options="header"]
|===

|ID
|Category
|Requirement  

|T.1 
|NIR light scanner  
a|As explained in <<Vein Toolbox Overview>>, the evaluator shall select the scanner from the following list  

* Commercial scanner 
* In-house scanner
* Camera

|T.2 
|Camera    
a|dSLR camera

* New dSLR camera shall be purchasable at the date of testing.
* The camera shall have been released within the previous 1 year period starting from the date of testing.
* Camera's resolution shall be at least 3 times higher than the TOE's sensor used for vein biometric verification.

|T.3 
|Printer             
a|Small Office/Home Office Inkjet printer

* New printer shall be purchasable at the date of testing.
* Test user's finger/palm shall be printed on a paper in full scale.

|===

== Materials Inventory

.Materials Requirements
[cols=".^1,.^1,3",options="header"]
|===

|ID
|Category
|Requirement

|M.1 
|Print paper            
a|Matte paper 

* Paper shall be wide enough to include a test user's finger/palm veins in full scale.

|M.2 
|Screen              
a|Mobile device screen

* The evaluator shall use the same mobile device used for capturing test user's finger/palm veins.
* Test user's finger/palm veins shall be displayed or replayed on the screen in full scale.

|M.3
|Bottle or Tube
a|A bottle or tube used to present a non-flat surface for the printed artefact

* A bottle or similar for a palm vein verification.
* A transparent tube roughly the size of a finger for finger vein verification.

|M.4
|Wax
|Wax that can be used to create the shape of the hand or wrist to cover the printed artefact.

|===
