= Attack L1-Vein VP1-04-xx
:xrefstyle: short

== Attack type
Video attack (visible light image)

=== Total Number of Species
This attack has *1* species to be tested.

== Overview
The evaluator displays a video of the target user's finger/palm veins on a screen and presents it to the TOE.

== Input
The finger/palm of non-cooperative subjects for use in capturing images of the subjects' vein pattern images. Images acquired under controlled and favorable conditions so as to acquire high quality vein pattern information.

== Common Attack Tools, Materials and Environment
* VP1-T.2 Camera
* VP1-M.2 Screen

== Common recipe
The evaluator captures a video of the target user's finger/palm veins using a dSLR camera, displays the video on a screen, begins video playback, and presents the screen to the TOE. The evaluator shall refer to publicly available information to change default settings of the camera to create clearer vein image artefacts. The evaluator shall record at least three 10 to 20 sec duration videos and select the best one to create each vein video artefact.

== Variations

None

== Penetration Testing and Attack Potential Rating Suggestions
=== Penetration Testing Suggestion
The evaluator should consider changing the following factors for penetration testing.

* Creation process, test subjects and presentation methods
+
The evaluator may change the creation process, test subject and presentation method as explained in <<BIOSD>> Section 6.3.1.3.1. 

=== Attack Potential Rating Suggestion
The attack potentials that are required to build the artefacts are summarized in the following tables. See BIOSD Section 9 for more information about how to calculate attack potential.

Attack Potential values are shown in <<calculatedtable>>. Attack Potential values for Identification account for the time, expertise, etc. required to make the recorded vein pattern video described in this attack. Attack potential for Exploitation corresponds to the effort to attack the TOE using the PAI in the actual environment (i.e., capturing the target vein pattern video from the subject and attack the TOE using the displayed vein pattern). <<calculatedtable>> shows the final attack potential to rate the vulnerabilities and TOE resistance.

*All Variations* 

.Calculated Attack Potential Vein attack 04-xx
[[calculatedtable]]
[cols=".^2,.^2,^.^1,.^2,^.^1,^.^1",options="header",]
|===
|Factor 
|Identification Value
|Score
|Exploitation Value
|Score
|Total

|*Elapsed Time*
|⇐ one day
|1
|<= one hour
|0
|1

|*Expertise*
|Layman
|0
|Layman
|0
|0

|*Knowledge of TOE*    
|Public
|0 
|Public
|0 
|0

|*Equipment*
|Standard
|0 
|Standard
|0
|0

a|
*Window of Opportunity*

*(Access to Biometric Characteristics)* 
|Not needed
|0
|Non-cooperative (Moderate)
|4
|4

a|
*Window of Opportunity*

*(Access to TOE)* 
|Easy
|0
|Moderate
|4
|4

|*Degree of Scrutiny*
|None
|0 
|None
|0
|0

6+^.^|Total Attack Potential = 9 &#8804; Basic Attack Potential

|===

== Pass Criteria
There are no additional criteria other than the criteria defined in <<BIOSD>> and <<PAD Toolbox Overview>>.
